stages:
  - test
  - deploy

build_maven_deploy:
  image: maven:3-jdk-8
  stage: deploy
  environment:
    name: Build test and deploy
  variables:
    PYTHONUNBUFFERED: "1"
    GEL_REPORT_MODELS_PYTHON_VERSION: "2"
  script:
    - set -x
    - curl -sL https://deb.nodesource.com/setup_11.x|bash -
    - apt update && apt install python-dev python-pip python-virtualenv libsasl2-dev libldap2-dev libssl-dev nodejs -y
    - npm install avrodoc -g
    - pip install --upgrade pip==9.0.3
    - pip install .
    - mvn -B -Dmaven.repo.local=.m2/repository -Pgelreportmodel-gitlab deploy 
  cache:
    paths:
      - .m2/repository/
  only:
    refs:
      - master


build_maven_test:
  image: maven:3-jdk-8
  stage: test
  environment:
    name: Build and test
  variables:
    PYTHONUNBUFFERED: "1"
    GEL_REPORT_MODELS_PYTHON_VERSION: "2"
  script:
    - set -x
    - curl -sL https://deb.nodesource.com/setup_11.x|bash -
    - apt update && apt install python-dev python-pip python-virtualenv libsasl2-dev libldap2-dev libssl-dev nodejs -y
    - npm install avrodoc -g
    - pip install --upgrade pip==9.0.3
    - pip install .
    - mvn -B -Dmaven.repo.local=.m2/repository -Pgelreportmodel-gitlab verify 
  cache:
    paths:
      - .m2/repository/


